# Generated by Django 2.2.17 on 2021-02-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='catergory',
            new_name='category',
        ),
    ]
